version: "3"
services:
  nginx:
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - 3000:80
  web:
    build:
      context: ./web
    container_name: web
    restart: always
  api:
    build:
      context: ./api
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/azure-sql-edge"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "tgalS59471!"
