# docker-compose.yml

version: "3"

services:
  web:
    build:
      context: ./the-greg-and-larry-show-web-app
      dockerfile: Dockerfile
    container_name: web
    restart: always
    # volumes:
    #   - ./the-greg-and-larry-show-web-app/:/app
    #   - /app/node_modules
    #   - /app/.next
    ports:
      - 3000:3000
  api:
    build:
      context: ./the-greg-and-larry-show-api
    ports:
      - 7004:7004
      - 5176:5176
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/azure-sql-edge"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "tgalS59471!"
    ports:
      - 1433:1433
