version: "3"
services:
  db:
    image: "mcr.microsoft.com/azure-sql-edge"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password1!
  nginx:
    depends_on:
      - api
      - web
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - 3000:80
  web:
    build:
      dockerfile: Dockerfile.dev
      context: ./web
    restart: always
  api:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
      context: ./api
    environment:
      - ASPNETCORE_HTTP_PORT=http://+:5001
      - ASPNETCORE_URLS=http://+:5000