version: 2.1
executors:
  docker-publisher:
    environment:
      WEB_IMAGE_NAME: mphbo777/greg-and-larry-web
      NGINX_IMAGE_NAME: mphbo777/greg-and-larry-nginx
      API_IMAGE_NAME: mphbo777/greg-and-larry-api
      
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Images
          command: | 
            docker build -t $WEB_IMAGE_NAME:latest ./web
            docker build -t $NGINX_IMAGE_NAME:latest ./nginx
            docker build -t $API_IMAGE_NAME:latest ./api
      - run:
          name: Archive Docker Images
          command: |
            docker save -o web.tar $WEB_IMAGE_NAME
            docker save -o nginx.tar $NGINX_IMAGE_NAME
            docker save -o api.tar $API_IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./web.tar
            - ./nginx.tar
            - ./api.tar
  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load Archived Docker Images
          command: |
            docker load -i /tmp/workspace/web.tar
            docker load -i /tmp/workspace/nginx.tar
            docker load -i /tmp/workspace/api.tar
      - run:
          name: Publish Docker Images to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $WEB_IMAGE_NAME:latest
            docker push $NGINX_IMAGE_NAME:latest
            docker push $API_IMAGE_NAME:latest
            docker push $WORKER_IMAGE_NAME:latest
workflows:
  version: 2
  build-main:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: main